### ISSUE TITLE
Error - "AltSign" is damage and cannot be opened

### ISSUE THREAD

**Issue by schults** [n3d1117/cook#1]
It seems there's some kind of bug after doing all the steps to add the cook mail plugin and executing "./cook -h"

Reason: no suitable image found.  Did find:
/Users/xxxxx/Downloads/cook/AltSign.framework/Versions/A/AltSign: code signature in (/Users/xxxx/Downloads/cook/AltSign.framework/Versions/A/AltSign) not valid for use in process using Library Validation: library load disallowed by system policy
/Users/xxxxx/Downloads/cook/AltSign.framework/Versions/A/AltSign: stat() failed with errno=1
Abort trap: 6

It says: “AltSign” is damaged and cannot be opened. You must move it to the Trash.

What can I do to fix this?

**Comment by dlevi309** [comment]
@schults what version of Mac OS are you on exactly?

**Comment by schults** [comment]
@dlevi309 Hey man, I'm using Catalina 10.15.2
Do you manage to use it? I can't use it here

**Comment by n3d1117** [comment]
Hello @schults, sorry for the late response!
- Can you confirm it still happens with latest release?
- Instead of using my release, have you tried building the project manally using Xcode?

**Comment by n3d1117** [comment]
Fixed in b20db6149465f9859be7cce9a972f61bdd16afaa as AltSign is now linked statically
