### ISSUE TITLE
CookMailPlugin - Incompatible Plug-ins Disabled

### ISSUE THREAD

**Issue by evandrix** [n3d1117/cook#2]
I got the same error as detailed at https://support.marketcircle.com/hc/en-us/articles/360036140454-When-I-launch-Mail-I-see-the-Incompatible-Plug-ins-Disabled-alert-

even though the Info.plist contains the correct UUID https://github.com/n3d1117/cook/blob/master/CookMailPlugin/CookMailPlugin/Info.plist#L61

I'm on Mac OSX 10.15.1 Catalina + Mail 13.0

**Comment by n3d1117** [comment]
Hello, sorry for the late response.
- Can you confirm that this is still happening with the latest cook release?
- Is the bundle correctly placed at `/Library/Mail/Bundles/`?
- Does the error still pop up even if you build the plugin yourself using Xcode?

**Comment by dlevi309** [comment]
I just figured out the solution to this issue, run the following command in terminal;

defaults write com.apple.mail EnableBundles -bool YES

Next time you launch the mail preferences, it should include a "Manage Plugins" option on the bottom of the page

**Comment by n3d1117** [comment]
Hi @dlevi309! Is your command any different from the one described in the README's `Installation` section?

`sudo defaults write "/Library/Preferences/com.apple.mail" EnableBundles 1`

**Comment by dlevi309** [comment]
Whoops, my bad bro, I didn't even see that 😳

**Comment by n3d1117** [comment]
Updated compatibility in 826219c2c2c2ead88578050fe6cc93cfdeebc667. Closing this for now, feel free to reopen if you're still having issues
